version: '3.8'

services:
  secret:
    entrypoint: sh ./docker-entrypoint.sh
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - storage:/app/storage
      - rails_log:/app/log
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
  storage:
  rails_log: