default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: secret_website_development

test:
  <<: *default
  database: secret_website_test

production:
  <<: *default
  database: secret_website_production